### ISSUE TITLE
Does it work with social login?

### ISSUE THREAD

**Issue by elie222** [kaskar2008/tgauth#4]
Does it only work with accounts-password or also with accounts-facebook, accounts-google, etc.?

**Comment by kaskar2008** [comment]
Why? It's sort of a different type of authorization. I used accounts-password package because of some features from it, so I think it's not necessary to use my package with facefook or google. If you could provide me a counter-example - maybe it will change my mind :)

**Comment by elie222** [comment]
I mean I have a meteor app already set up, and some users are signed up through google, facebook and some just regular password signup.
Would this package not work to authenticate with the already existing facebook signup users?

**Comment by kaskar2008** [comment]
Now I see. As much as I know google or facebook login types create new user if not exists, right? And it is done with default users collection. So I think it wan't be a problem to use tgauth with different types of authorizations. It's just because I'm using token creation and loging in with it - it's accounts-base package's feature. You could test it on your project if you have dev or local copy :) And if you will do this test please leave your results here. I'll try to fix errors if there will be any issues ;)

**Comment by elie222** [comment]
i will try have a look in the next few days. thanks

**Comment by kaskar2008** [comment]
You have to keep in mind one thing - somehow on your project your google or facebook users must link their accounts to the telegram (it's up to you how to do that). Anyway in default account information must be a field with telegram user ID in profile object. "profile.tgId". Than you can easily log in.

**Comment by elie222** [comment]
Ok thanks. Sticking it in the profile field isn't safe though. It will get
published to other users too.
On 25 Apr 2016 15:41, "Karen" notifications@github.com wrote:

You have to keep in mind one thing - somehow on your project your google or
facebook users must link their accounts to the telegram (it's up to you how
to do that). Anyway in default account information must be a field with
telegram user ID in profile object. "profile.tgId". Than you can easily log
in.
